//Test code generated by MISTA

import junit.framework.*;

public class ControllerTester_RTD extends TestCase{

	private Controller controller;
	
	protected void setUp()  throws Exception {
		controller = new Controller();
	}
	
	public void test1() throws Exception {
		System.out.println("Test case 1");
		try {
			controller.engineOff();
			System.out.println("Test failed at test 1_1: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_1", controller.INACTIVE());
	}

	public void test2() throws Exception {
		System.out.println("Test case 2");
		controller.engineOn();
		assertTrue("1_2", controller.ACTIVE());
		controller.engineOff();
		assertTrue("1_2_1", controller.INACTIVE());
	}

	public void test3() throws Exception {
		System.out.println("Test case 3");
		controller.engineOn();
		try {
			controller.engineOn();
			System.out.println("Test failed at test 1_2_2: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_2_2", controller.ACTIVE());
	}

	public void test4() throws Exception {
		System.out.println("Test case 4");
		controller.engineOn();
		controller.brake();
		assertTrue("1_2_3", controller.ACTIVE());
	}

	public void test5() throws Exception {
		System.out.println("Test case 5");
		controller.engineOn();
		controller.accelerator();
		assertTrue("1_2_4", controller.ACTIVE());
	}

	public void test6() throws Exception {
		System.out.println("Test case 6");
		controller.engineOn();
		try {
			controller.resume();
			System.out.println("Test failed at test 1_2_5: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_2_5", controller.ACTIVE());
	}

	public void test7() throws Exception {
		System.out.println("Test case 7");
		controller.engineOn();
		controller.on();
		assertTrue("1_2_6", controller.CRUISING());
		controller.engineOff();
		assertTrue("1_2_6_1", controller.INACTIVE());
	}

	public void test8() throws Exception {
		System.out.println("Test case 8");
		controller.engineOn();
		controller.on();
		try {
			controller.engineOn();
			System.out.println("Test failed at test 1_2_6_2: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_2_6_2", controller.CRUISING());
	}

	public void test9() throws Exception {
		System.out.println("Test case 9");
		controller.engineOn();
		controller.on();
		controller.brake();
		assertTrue("1_2_6_3", controller.STANDBY());
		controller.engineOff();
		assertTrue("1_2_6_3_1", controller.INACTIVE());
	}

	public void test10() throws Exception {
		System.out.println("Test case 10");
		controller.engineOn();
		controller.on();
		controller.brake();
		try {
			controller.engineOn();
			System.out.println("Test failed at test 1_2_6_3_2: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_2_6_3_2", controller.STANDBY());
	}

	public void test11() throws Exception {
		System.out.println("Test case 11");
		controller.engineOn();
		controller.on();
		controller.brake();
		try {
			controller.brake();
			System.out.println("Test failed at test 1_2_6_3_3: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_2_6_3_3", controller.STANDBY());
	}

	public void test12() throws Exception {
		System.out.println("Test case 12");
		controller.engineOn();
		controller.on();
		controller.brake();
		try {
			controller.accelerator();
			System.out.println("Test failed at test 1_2_6_3_4: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_2_6_3_4", controller.STANDBY());
	}

	public void test13() throws Exception {
		System.out.println("Test case 13");
		controller.engineOn();
		controller.on();
		controller.brake();
		controller.resume();
		assertTrue("1_2_6_3_5", controller.CRUISING());
	}

	public void test14() throws Exception {
		System.out.println("Test case 14");
		controller.engineOn();
		controller.on();
		controller.brake();
		controller.on();
		assertTrue("1_2_6_3_6", controller.CRUISING());
	}

	public void test15() throws Exception {
		System.out.println("Test case 15");
		controller.engineOn();
		controller.on();
		controller.brake();
		try {
			controller.off();
			System.out.println("Test failed at test 1_2_6_3_7: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_2_6_3_7", controller.STANDBY());
	}

	public void test16() throws Exception {
		System.out.println("Test case 16");
		controller.engineOn();
		controller.on();
		controller.accelerator();
		assertTrue("1_2_6_4", controller.STANDBY());
	}

	public void test17() throws Exception {
		System.out.println("Test case 17");
		controller.engineOn();
		controller.on();
		try {
			controller.resume();
			System.out.println("Test failed at test 1_2_6_5: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_2_6_5", controller.CRUISING());
	}

	public void test18() throws Exception {
		System.out.println("Test case 18");
		controller.engineOn();
		controller.on();
		try {
			controller.on();
			System.out.println("Test failed at test 1_2_6_6: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_2_6_6", controller.CRUISING());
	}

	public void test19() throws Exception {
		System.out.println("Test case 19");
		controller.engineOn();
		controller.on();
		controller.off();
		assertTrue("1_2_6_7", controller.STANDBY());
	}

	public void test20() throws Exception {
		System.out.println("Test case 20");
		controller.engineOn();
		try {
			controller.off();
			System.out.println("Test failed at test 1_2_7: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_2_7", controller.ACTIVE());
	}

	public void test21() throws Exception {
		System.out.println("Test case 21");
		try {
			controller.brake();
			System.out.println("Test failed at test 1_3: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_3", controller.INACTIVE());
	}

	public void test22() throws Exception {
		System.out.println("Test case 22");
		try {
			controller.accelerator();
			System.out.println("Test failed at test 1_4: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_4", controller.INACTIVE());
	}

	public void test23() throws Exception {
		System.out.println("Test case 23");
		try {
			controller.resume();
			System.out.println("Test failed at test 1_5: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_5", controller.INACTIVE());
	}

	public void test24() throws Exception {
		System.out.println("Test case 24");
		try {
			controller.on();
			System.out.println("Test failed at test 1_6: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_6", controller.INACTIVE());
	}

	public void test25() throws Exception {
		System.out.println("Test case 25");
		try {
			controller.off();
			System.out.println("Test failed at test 1_7: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_7", controller.INACTIVE());
	}

}
